
document.addEventListener("DOMContentLoaded", function () {
  // Hide Events for employees
  if (inSidedData.user.role.includes('Employee')) { 
    document.querySelectorAll('li.header-navigation_list-item a').forEach(link => {
      if (link.classList.contains('title-events')) {
        link.closest('li').style.display = 'none';
      }
    });
  }
  
  
  // ADD CUSTOM MENU ITEM WITH CHILD ITEMS
  window.customMegaMenuItems = [
    {
      key: "custom-dropdown", // Must remain "custom-dropdown"
      position: 99,
      visibility: true,
      name: "Security Forums",
      roles: [],
      children: [
        {
          id: 1,
          displayOrder: "1",
          title: "SecOps SIEM",
          url: "https://www.googlecloudcommunity.com/gc/SecOps-SIEM/bd-p/chronicle-siem",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 2,
          displayOrder: "2",
          title: "SecOps SOAR",
          url: "https://www.googlecloudcommunity.com/gc/SecOps-SOAR/bd-p/chronicle-soar",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 3,
          displayOrder: "3",
          title: "Google Threat Intelligence",
          url: "https://www.googlecloudcommunity.com/gc/Google-Threat-Intelligence/bd-p/threat-intelligence-forum",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 4,
          displayOrder: "4",
          title: "Security Command Center",
          url: "https://www.googlecloudcommunity.com/gc/Security-Command-Center/bd-p/command-ctr-forum",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 5,
          displayOrder: "5",
          title: "Attack Surface Management",
          url: "https://www.googlecloudcommunity.com/gc/Attack-Surface-Management/bd-p/mandiant-attack-surface-mgmt",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 6,
          displayOrder: "6",
          title: "Mandiant Threat Defense",
          url: "https://www.googlecloudcommunity.com/gc/Mandiant-Threat-Defense/bd-p/mandiant-managed-defense",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 7,
          displayOrder: "7",
          title: "Security Validation",
          url: "https://www.googlecloudcommunity.com/gc/Security-Validation/bd-p/mandiant-security-validation",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 8,
          displayOrder: "8",
          title: "reCAPTCHA",
          url: "https://www.googlecloudcommunity.com/gc/reCAPTCHA/bd-p/recaptcha-forum",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        },
        {
          id: 9,
          displayOrder: "9",
          title: "Security Foundation",
          url: "https://www.googlecloudcommunity.com/gc/Security-Foundation/bd-p/security-foundation",
          type: 1,
          description: "",
          heroImage: "",
          thumbnailImage: "",
          showDescriptionOnHomepage: false,
          replyCount: 0,
          children: [],
          topicsOrder: [],
          isCollapsed: false,
          metaRobots: "index,follow",
          seoTitle: "",
          seoDescription: "",
          hideFromSearch: false,
          includeForStats: true,
          parentId: null,
          isContainer: false,
          roles: []
        }
      ]
    }
  ];
});
